# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration. 
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: python:3.5.1
#image: python:2.7.15
# this image allows conda to install gsl
#image: continuumio/miniconda3:latest
image: continuumio/anaconda3:latest
#image: continuumio/anaconda:latest

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - export DEBIAN_FRONTEND=noninteractive
          - apt-get -yq install gcc
          - apt-get -yq install libgsl-dev
          #- conda install -y -c anaconda gcc
          #- conda install -y -c conda-forge gsl 
          - pip install pytest
          - pip install scipy
          - pip install gwtools
          - pip install h5py
          - pip install scikit-learn
          - git submodule init
          - git submodule update
          - cd ..
          - pip install -e build/ # install from local setup.py
          - cd build
          - python test/download_regression_models.py
          - pytest
